# Store Type creation script using kfutil
# Generated by Doctool

Write-Host "Creating store type: ONTAP_CERTS"
kfutil store-types create ONTAP_CERTS

Write-Host "Creating store type: ONTAP_TRUSTED"
kfutil store-types create ONTAP_TRUSTED

