# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: ONTAP_CERTS"
$Body = @'
{
  "Name": "NetApp ONTAP Certificates",
  "ShortName": "ONTAP_CERTS",
  "Capability": "ONTAP_CERTS",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "When enabled, TLS certificate validation is skipped when connecting to the ONTAP management endpoint. Useful for lab clusters and the ONTAP Simulator, which present a self-signed certificate. Leave disabled for production clusters that present a trusted certificate."
    }
  ],
  "EntryParameters": [
    {
      "Name": "CertType",
      "DisplayName": "Certificate Type",
      "Description": "The ONTAP certificate 'type' to install this entry as. 'server' installs a certificate + private key used by ONTAP acting as an SSL server; 'client' installs a certificate + private key used by ONTAP acting as an SSL client. Required when adding a certificate.",
      "Type": "MultipleChoice",
      "Options": "server,client",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": true,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": "server"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Required",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: ONTAP_TRUSTED"
$Body = @'
{
  "Name": "NetApp ONTAP Trusted Roots",
  "ShortName": "ONTAP_TRUSTED",
  "Capability": "ONTAP_TRUSTED",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "When enabled, TLS certificate validation is skipped when connecting to the ONTAP management endpoint. Useful for lab clusters and the ONTAP Simulator, which present a self-signed certificate. Leave disabled for production clusters that present a trusted certificate."
    }
  ],
  "EntryParameters": [
    {
      "Name": "CertType",
      "DisplayName": "Certificate Type",
      "Description": "The ONTAP trust-anchor 'type' to install this entry as. 'server_ca' is trusted by ONTAP acting as an SSL client to verify an external server; 'client_ca' is trusted by ONTAP acting as an SSL server to verify an incoming client certificate. Required when adding a certificate. Trust anchors are public certificates only; no private key is installed.",
      "Type": "MultipleChoice",
      "Options": "server_ca,client_ca",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": true,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": "server_ca"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Forbidden",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

