#!/bin/bash
# Store Type creation script using curl
# Generated by Doctool

set -e

# Configuration - set these variables before running
KEYFACTOR_HOSTNAME="${KEYFACTOR_HOSTNAME}"
KEYFACTOR_API_PATH="${KEYFACTOR_API_PATH:-KeyfactorAPI}"
KEYFACTOR_AUTH_TOKEN="${KEYFACTOR_AUTH_TOKEN}"

echo "Creating store type: ONTAP_CERTS"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "NetApp ONTAP Certificates",
  "ShortName": "ONTAP_CERTS",
  "Capability": "ONTAP_CERTS",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "When enabled, TLS certificate validation is skipped when connecting to the ONTAP management endpoint. Useful for lab clusters and the ONTAP Simulator, which present a self-signed certificate. Leave disabled for production clusters that present a trusted certificate."
    }
  ],
  "EntryParameters": [
    {
      "Name": "CertType",
      "DisplayName": "Certificate Type",
      "Description": "The ONTAP certificate 'type' to install this entry as. 'server' installs a certificate + private key used by ONTAP acting as an SSL server; 'client' installs a certificate + private key used by ONTAP acting as an SSL client. Required when adding a certificate.",
      "Type": "MultipleChoice",
      "Options": "server,client",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": true,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": "server"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Required",
  "JobProperties": [
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DefaultValue": "false",
      "Required": false,
      "Description": "When enabled on a Discovery job, TLS certificate validation is skipped when connecting to the ONTAP management endpoint. Useful for lab clusters and the ONTAP Simulator."
    }
  ],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'

echo "Creating store type: ONTAP_TRUSTED"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "NetApp ONTAP Trusted Roots",
  "ShortName": "ONTAP_TRUSTED",
  "Capability": "ONTAP_TRUSTED",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "When enabled, TLS certificate validation is skipped when connecting to the ONTAP management endpoint. Useful for lab clusters and the ONTAP Simulator, which present a self-signed certificate. Leave disabled for production clusters that present a trusted certificate."
    }
  ],
  "EntryParameters": [
    {
      "Name": "CertType",
      "DisplayName": "Certificate Type",
      "Description": "The ONTAP trust-anchor 'type' to install this entry as. 'server_ca' is trusted by ONTAP acting as an SSL client to verify an external server; 'client_ca' is trusted by ONTAP acting as an SSL server to verify an incoming client certificate. Required when adding a certificate. Trust anchors are public certificates only; no private key is installed.",
      "Type": "MultipleChoice",
      "Options": "server_ca,client_ca",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": true,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DefaultValue": "server_ca"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Forbidden",
  "JobProperties": [
    {
      "Name": "IgnoreSSLWarning",
      "DisplayName": "Ignore SSL Warning",
      "Type": "Bool",
      "DefaultValue": "false",
      "Required": false,
      "Description": "When enabled on a Discovery job, TLS certificate validation is skipped when connecting to the ONTAP management endpoint. Useful for lab clusters and the ONTAP Simulator."
    }
  ],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required"
}'

