#!/bin/bash
# Store Type creation script using kfutil
# Generated by Doctool

set -e

echo "Creating store type: ONTAP_CERTS"
kfutil store-types create ONTAP_CERTS

echo "Creating store type: ONTAP_TRUSTED"
kfutil store-types create ONTAP_TRUSTED

